### PR TITLE
Show more progress data

### LINKED ISSUE #10: progress show more data
perhaps the progress indicator can show other things like what step of the process its on (eg making project, renaming...)

those don't need to be percentages, (i dont think thats possible anyways).

the main reason for this is because the indicator shows up a bit later (only when the actual upload begins) and thats makes it feel slightly slow.

### PR DESCRIPTION
**Pull request by BoomerScratch**
Resolves #10
Adds "Reading file...", "Creating project...", "Naming project...", "Uploading thumbnail..." and "Moving project to trash...".

### CODE REVIEW

**Comment by JeffaloBob** [comment]
it doesn't seem to be working for me.
image

**Comment by BoomerScratch** [comment]
@JeffaloBob Hmm... That's weird... Let me check.

**Comment by JeffaloBob** [comment]
> @JeffaloBob Hmm... That's weird... Let me check.

thanks

**Comment by BoomerScratch** [comment]
@JeffaloBob It works as expected for me. I'm using a userscript.

**Comment by BoomerScratch** [comment]
I'm gonna try something else.

**Comment by JeffaloBob** [comment]
> @JeffaloBob It works as expected for me. I'm using a userscript.

hmmm i'll see if i can fix it

**Comment by JeffaloBob** [comment]
> I'm gonna try something else.

oh alright

**Comment by BoomerScratch** [comment]
@JeffaloBob Can you try again now? I pushed a new commit.

**Comment by JeffaloBob** [comment]
alright i'll test it

**Comment by JeffaloBob** [comment]
image
atleast, it's a new error this time...

**Comment by JeffaloBob** [comment]
i'll see if i can fix it

**Comment by BoomerScratch** [comment]
The variable is `undefined`, and I don't know why.

**Comment by JeffaloBob** [comment]
> The variable is `undefined`, and I don't know why.

thats really odd

**Comment by JeffaloBob** [comment]
ok, i have a really simple version of this working, but i have a question about the percentage when uploading thumbnail.

does it ever show anything other than 0 or 100? perhaps my images are too small or something but i cant get it to show anything in between.

**Comment by BoomerScratch** [comment]
@JeffaloBob Yes. If you upload a bigger image you might be able to see it.

**Comment by JeffaloBob** [comment]
> @JeffaloBob Yes. If you upload a bigger image you might be able to see it.

yep! i was about to edit my comment. i slowed down my connection and i saw it.

thanks though! i'll close this PR and add my changes in a min. :)

**Comment by BoomerScratch** [comment]
@JeffaloBob k. I don't know what is going wrong. Maybe declare the variable with `let`?

**Comment by JeffaloBob** [comment]
> @JeffaloBob k. I don't know what is going wrong. Maybe declare the variable with `let`?

yeah there something weird happening, my fix was basic and it's missing some error handling but that can be added later i guess ¯\_(ツ)_/¯

**Pull request closed without merging**
