### PR TITLE
Use raw.githubusercontent.com instead of a data URL

### LINKED ISSUE #3: make the upload button load with the other ones
i dont know if this is possible, but i was wondering if maybe the upload button could load with the other buttons to make it a bit less jarring. i think this could be possible by not loading the other buttons until the upload button is also ready, but this is my first time making an extenstion like this so i dont know if this is really possible

### PR DESCRIPTION
**Pull request by BoomerScratch**
Resolves #3
This uses raw.githubusercontent.com instead of a data URL. When using a data URL, the browser only has to base64 decode the image, making it load faster. When you use raw.githubusercontent.com, it needs to request the image and wait for a response, making it take longer to load. That should make the buttons look like they load at the same time.

I was unable to test this, because well, you know. If you want to test this, merge this PR, and test it. If it doesn't work, don't worry! Simply revert this pull request. If the image of the button doesn't work, wait for some time and try again (because of the server speed).

### CODE REVIEW

**Comment by BoomerScratch** [comment]
@JeffaloBob This is how the loading looks like with this PR merged:

Looks good to me, right?
You should hard refresh when testing it. It becoming wider is the userscript timing (because I use the userscript).

**Comment by JeffaloBob** [comment]
how about when the data urls are used?

**Comment by BoomerScratch** [comment]
@JeffaloBob Then the button loads about a second earlier.

**Comment by JeffaloBob** [comment]
> @JeffaloBob Then the button loads about a second earlier.

wait earlier? or later im confused lol

**Comment by BoomerScratch** [comment]
@JeffaloBob:

**Comment by easrng** [comment]
> i wonder if this'll break @easrng <https://github.com/easrng>'s userstyle
which adds material forum buttons.

also i mean, it's a tiny base64 encoded image, it could take longer to
fetch the github url. but i dont know. i'll add a needs discussion label.

It won't break it. Why change this though? With a data URL, it downloads
once, with the userscript, while if you host it, it downloads every time.

**Comment by JeffaloBob** [comment]
yeah i think this might end up being slower/less reliable than a data url so i dont think we need it sorry :(

**Pull request closed without merging**
