### PR TITLE
Add visual feedback for drag and drop

### LINKED ISSUE #15: visual feedback for drag and drop
when dragging and dropping have some kind of visual feedback that you can drop

### PR DESCRIPTION
**Pull request by BoomerScratch**
Resolves #15 
The text area will become grey when dragged over. Adding text telling the user to drag and drop was hard, so I skipped it.

### CODE REVIEW

**Comment by JeffaloBob** [comment]
thanks! but when i drag in an image instead of uploading it it opens it in a new tab.
maybe there needs to be a `e.preventDefault() `somewhere?

**Comment by BoomerScratch** [comment]
@JeffaloBob Is it fixed now?

**Comment by JeffaloBob** [comment]
yep! awesome thanks!

**Comment by JeffaloBob** [comment]
i wonder if they are any downsides to setting an attribute instead of using css or something. i guess we'll see lol

**Pull request merged**
